//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj5.CityPopService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CityPopService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SolarIntensity", ReplyAction="http://tempuri.org/IService1/SolarIntensityResponse")]
        decimal SolarIntensity(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SolarIntensity", ReplyAction="http://tempuri.org/IService1/SolarIntensityResponse")]
        System.Threading.Tasks.Task<decimal> SolarIntensityAsync(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10Words", ReplyAction="http://tempuri.org/IService1/Top10WordsResponse")]
        string[] Top10Words(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10Words", ReplyAction="http://tempuri.org/IService1/Top10WordsResponse")]
        System.Threading.Tasks.Task<string[]> Top10WordsAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WindIntensity", ReplyAction="http://tempuri.org/IService1/WindIntensityResponse")]
        decimal WindIntensity(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WindIntensity", ReplyAction="http://tempuri.org/IService1/WindIntensityResponse")]
        System.Threading.Tasks.Task<decimal> WindIntensityAsync(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HailIntensity", ReplyAction="http://tempuri.org/IService1/HailIntensityResponse")]
        decimal HailIntensity(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HailIntensity", ReplyAction="http://tempuri.org/IService1/HailIntensityResponse")]
        System.Threading.Tasks.Task<decimal> HailIntensityAsync(decimal latitude, decimal longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationPop", ReplyAction="http://tempuri.org/IService1/LocationPopResponse")]
        decimal LocationPop(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LocationPop", ReplyAction="http://tempuri.org/IService1/LocationPopResponse")]
        System.Threading.Tasks.Task<decimal> LocationPopAsync(string cityName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Proj5.CityPopService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Proj5.CityPopService.IService1>, Proj5.CityPopService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal SolarIntensity(decimal latitude, decimal longitude) {
            return base.Channel.SolarIntensity(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<decimal> SolarIntensityAsync(decimal latitude, decimal longitude) {
            return base.Channel.SolarIntensityAsync(latitude, longitude);
        }
        
        public string[] Top10Words(string url) {
            return base.Channel.Top10Words(url);
        }
        
        public System.Threading.Tasks.Task<string[]> Top10WordsAsync(string url) {
            return base.Channel.Top10WordsAsync(url);
        }
        
        public decimal WindIntensity(decimal latitude, decimal longitude) {
            return base.Channel.WindIntensity(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<decimal> WindIntensityAsync(decimal latitude, decimal longitude) {
            return base.Channel.WindIntensityAsync(latitude, longitude);
        }
        
        public decimal HailIntensity(decimal latitude, decimal longitude) {
            return base.Channel.HailIntensity(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<decimal> HailIntensityAsync(decimal latitude, decimal longitude) {
            return base.Channel.HailIntensityAsync(latitude, longitude);
        }
        
        public decimal LocationPop(string cityName) {
            return base.Channel.LocationPop(cityName);
        }
        
        public System.Threading.Tasks.Task<decimal> LocationPopAsync(string cityName) {
            return base.Channel.LocationPopAsync(cityName);
        }
    }
}
